/* Explanations of OSCAR's controls
 *
 * Copyright (c) 2026 The OSCAR Team
 *
 * This file is subject to the terms and conditions of the GNU General Public
 * License. See the file COPYING in the main directory of the source code
 * for more details. */

#include "uiglossary.h"

#include <QCoreApplication>
#include <QStringList>

#include "glossary.h"

namespace {

// clang-format off
const UiGlossaryRaw kUiEntries[] = {
    // ---- menus, main window, Daily, Overview, home page
    { "ui.menu.actionDatabaseNew", QT_TRANSLATE_NOOP("Glossary", "New database"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Database"),
      QT_TRANSLATE_NOOP("Glossary", "Creates an empty OSCAR database in a folder you choose and switches to it."),
      QT_TRANSLATE_NOOP("Glossary", "Needed only to keep completely separate data, for example for another family member on another computer; one database holds several profiles anyway."),
      QT_TRANSLATE_NOOP("Glossary", "OSCAR switches to the new, empty database; your current data stays in its old folder."), "" },
    { "ui.menu.actionDatabaseOpen", QT_TRANSLATE_NOOP("Glossary", "Open database"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Database"),
      QT_TRANSLATE_NOOP("Glossary", "Switches OSCAR to another existing database folder."),
      QT_TRANSLATE_NOOP("Glossary", "Use it to return to a database you made earlier or copied from another computer."),
      QT_TRANSLATE_NOOP("Glossary", "OSCAR closes the current database and shows only the data of the opened one."), "" },
    { "ui.menu.actionDatabaseDelete", QT_TRANSLATE_NOOP("Glossary", "Delete database"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Database"),
      QT_TRANSLATE_NOOP("Glossary", "Deletes an OSCAR database that is not open now, with all its profiles and nights."),
      QT_TRANSLATE_NOOP("Glossary", "Make a backup of the profile first if you may need the data again."),
      QT_TRANSLATE_NOOP("Glossary", "The folder and everything in it are deleted for good."), "" },
    { "ui.menu.action_Import_Data", QT_TRANSLATE_NOOP("Glossary", "Import CPAP card data"),
      QT_TRANSLATE_NOOP("Glossary", "File menu"),
      QT_TRANSLATE_NOOP("Glossary", "Reads the new nights from the device's SD card or its copy on the computer."),
      QT_TRANSLATE_NOOP("Glossary", "Insert the card and choose it. Nights already in OSCAR are skipped, so importing the same card again is safe."),
      "", "sessions" },
    { "ui.menu.action_Preferences", QT_TRANSLATE_NOOP("Glossary", "Preferences"),
      QT_TRANSLATE_NOOP("Glossary", "File menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the settings of OSCAR and of the current profile: import, graphs, oximetry, analysis and more."),
      QT_TRANSLATE_NOOP("Glossary", "Each setting explains itself in the strip at the bottom of the window when you hover it."),
      "", "" },
    { "ui.menu.action_Edit_Profile", QT_TRANSLATE_NOOP("Glossary", "Edit profile"),
      QT_TRANSLATE_NOOP("Glossary", "File menu"),
      QT_TRANSLATE_NOOP("Glossary", "Changes the profile's name, date of birth, height, doctor's details and the device data."),
      QT_TRANSLATE_NOOP("Glossary", "Height is used for BMI on the Daily page when you enter your weight."),
      "", "" },
    { "ui.menu.actionPrint_Report", QT_TRANSLATE_NOOP("Glossary", "Print report"),
      QT_TRANSLATE_NOOP("Glossary", "File menu"),
      QT_TRANSLATE_NOOP("Glossary", "Prints the page you are looking at: the selected day, the Overview graphs or the Statistics."),
      QT_TRANSLATE_NOOP("Glossary", "For the doctor, \"Create PDF Report\" gives one file with all the main figures."),
      "", "" },
    { "ui.menu.actionPdf_Report", QT_TRANSLATE_NOOP("Glossary", "Create PDF report"),
      QT_TRANSLATE_NOOP("Glossary", "File menu"),
      QT_TRANSLATE_NOOP("Glossary", "Makes one PDF for the doctor: a summary of the period, the statistics, chosen nights and graphs."),
      QT_TRANSLATE_NOOP("Glossary", "Choose the period and the parts in the window that opens; the settings are remembered for next time."),
      "", "ahi,compliance" },
    { "ui.menu.actionExport_CSV", QT_TRANSLATE_NOOP("Glossary", "CSV export wizard"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Export Data"),
      QT_TRANSLATE_NOOP("Glossary", "Saves the data as CSV tables for a spreadsheet: summaries by day or session, or every event."),
      QT_TRANSLATE_NOOP("Glossary", "Open the file in Excel or Numbers. For the doctor a PDF report is usually easier."),
      "", "" },
    { "ui.menu.actionExport_V1_CSV", QT_TRANSLATE_NOOP("Glossary", "Version 1 CSV reports"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Export Data"),
      QT_TRANSLATE_NOOP("Glossary", "Saves CSV files in the format of the old OSCAR 1.7."),
      QT_TRANSLATE_NOOP("Glossary", "Only for tools that read that old format."),
      "", "" },
    { "ui.menu.actionExport_Journal_Notes", QT_TRANSLATE_NOOP("Glossary", "Export journal notes"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Export Data"),
      QT_TRANSLATE_NOOP("Glossary", "Saves the notes of a range of days as an HTML or Markdown file."),
      "",
      "", "" },
    { "ui.menu.action_Import_OSCAR_Data", QT_TRANSLATE_NOOP("Glossary", "Import from OSCAR"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Profiles"),
      QT_TRANSLATE_NOOP("Glossary", "Brings in a profile from the older OSCAR that kept its data in files instead of a database."),
      QT_TRANSLATE_NOOP("Glossary", "Needed once, when you move from the old OSCAR to this one."),
      "", "" },
    { "ui.menu.actionBackup_Profile", QT_TRANSLATE_NOOP("Glossary", "Back up profile"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Profiles"),
      QT_TRANSLATE_NOOP("Glossary", "Saves the whole current profile to one .oscar file."),
      QT_TRANSLATE_NOOP("Glossary", "Make a backup before big changes and keep a copy outside the computer."),
      "", "" },
    { "ui.menu.actionRestore_Profile", QT_TRANSLATE_NOOP("Glossary", "Restore profile"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Profiles"),
      QT_TRANSLATE_NOOP("Glossary", "Loads a profile from a .oscar backup file."),
      QT_TRANSLATE_NOOP("Glossary", "Check the date of the backup before restoring."),
      QT_TRANSLATE_NOOP("Glossary", "Restoring over an existing profile replaces its data with the backup's."), "" },
    { "ui.menu.actionShare_Profile", QT_TRANSLATE_NOOP("Glossary", "Share profile"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Profiles"),
      QT_TRANSLATE_NOOP("Glossary", "Prepares a copy of the profile's data to give to another OSCAR user, for example a helper on a forum."),
      QT_TRANSLATE_NOOP("Glossary", "You choose what to leave out, such as personal details."),
      "", "" },
    { "ui.menu.actionExport_Journal", QT_TRANSLATE_NOOP("Glossary", "Export journal"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Journals"),
      QT_TRANSLATE_NOOP("Glossary", "Saves the journal (notes, weight, feelings, bookmarks) to a file."),
      "",
      "", "" },
    { "ui.menu.actionImport_Journal", QT_TRANSLATE_NOOP("Glossary", "Import journal"),
      QT_TRANSLATE_NOOP("Glossary", "File menu → Journals"),
      QT_TRANSLATE_NOOP("Glossary", "Loads a journal file saved by \"Export Journal\"."),
      "",
      "", "" },
    { "ui.menu.action_Exit", QT_TRANSLATE_NOOP("Glossary", "Exit"),
      QT_TRANSLATE_NOOP("Glossary", "File menu"),
      QT_TRANSLATE_NOOP("Glossary", "Closes OSCAR. Everything is already saved in the database."),
      "",
      "", "" },
    { "ui.menu.actionView_Daily", QT_TRANSLATE_NOOP("Glossary", "Daily view"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Daily page: one night in detail, with graphs and events."),
      "",
      "", "" },
    { "ui.menu.actionView_Overview", QT_TRANSLATE_NOOP("Glossary", "Overview"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Overview page: one bar per night for a chosen period."),
      "",
      "", "" },
    { "ui.menu.actionView_Statistics", QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Statistics page: tables of the figures for the last night, week, month and longer."),
      "",
      "", "median,p95" },
    { "ui.menu.action_Fullscreen", QT_TRANSLATE_NOOP("Glossary", "Maximize"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Switches the window between full screen and its normal size."),
      "",
      "", "" },
    { "ui.menu.action_Screenshot", QT_TRANSLATE_NOOP("Glossary", "Take screenshot"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Saves a picture of the OSCAR window to the screenshots folder."),
      QT_TRANSLATE_NOOP("Glossary", "Handy for asking for advice on a forum."),
      "", "" },
    { "ui.menu.action_Standard_Graph_Order", QT_TRANSLATE_NOOP("Glossary", "Standard graph order"),
      QT_TRANSLATE_NOOP("Glossary", "View menu → Reset Graphs"),
      QT_TRANSLATE_NOOP("Glossary", "Puts the Daily graphs back in the order suited to CPAP and APAP devices."),
      QT_TRANSLATE_NOOP("Glossary", "Use it for Prisma 20A, Resvent and other CPAP/APAP devices."),
      QT_TRANSLATE_NOOP("Glossary", "Your own order of the graphs is replaced."), "" },
    { "ui.menu.action_Advanced_Graph_Order", QT_TRANSLATE_NOOP("Glossary", "Advanced graph order"),
      QT_TRANSLATE_NOOP("Glossary", "View menu → Reset Graphs"),
      QT_TRANSLATE_NOOP("Glossary", "Puts the Daily graphs in the order suited to bilevel and ASV devices."),
      QT_TRANSLATE_NOOP("Glossary", "Only for BPAP with a backup rate, ASV, AVAPS and similar devices."),
      QT_TRANSLATE_NOOP("Glossary", "Your own order of the graphs is replaced."), "" },
    { "ui.menu.action_Reset_Graph_Layout", QT_TRANSLATE_NOOP("Glossary", "Reset graph heights"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Makes all graphs their standard height again."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "The heights you set by dragging are lost."), "" },
    { "ui.menu.actionLine_Cursor", QT_TRANSLATE_NOOP("Glossary", "Line cursor"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows a vertical line across all Daily graphs at the mouse position."),
      QT_TRANSLATE_NOOP("Glossary", "Helps to see what every channel did at the same moment, for example at an apnea."),
      "", "" },
    { "ui.menu.actionPie_Chart", QT_TRANSLATE_NOOP("Glossary", "Pie chart"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows a pie of the event types on the Daily page."),
      "",
      "", "" },
    { "ui.menu.actionLeft_Daily_Sidebar", QT_TRANSLATE_NOOP("Glossary", "Daily sidebar"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows or hides the left panel of the Daily page with the night's details."),
      "",
      "", "" },
    { "ui.menu.actionDaily_Calendar", QT_TRANSLATE_NOOP("Glossary", "Daily calendar"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows or hides the calendar on the Daily page."),
      "",
      "", "" },
    { "ui.menu.action_Sidebar_Toggle", QT_TRANSLATE_NOOP("Glossary", "Right sidebar"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows or hides the right sidebar with the profile and bookmarks."),
      "",
      "", "" },
    { "ui.menu.actionShowPersonalData", QT_TRANSLATE_NOOP("Glossary", "Show personal data"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows or hides the name and other personal details on the pages and reports."),
      QT_TRANSLATE_NOOP("Glossary", "Turn it off before taking screenshots for a forum."),
      "", "" },
    { "ui.menu.actionHoverExplanations", QT_TRANSLATE_NOOP("Glossary", "Hover explanations"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Turns on or off these explanations when the mouse rests on a figure, a term, a menu item or a setting."),
      QT_TRANSLATE_NOOP("Glossary", "If the pop-ups get in the way, turn them off here; the old short tooltips stay."),
      "", "" },
    { "ui.menu.actionHelpPanel", QT_TRANSLATE_NOOP("Glossary", "Help panel"),
      QT_TRANSLATE_NOOP("Glossary", "View menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows or hides the panel on the right with the full explanation of the last thing hovered and a search of all explanations."),
      "",
      "", "" },
    { "ui.menu.actionView_Oximetry", QT_TRANSLATE_NOOP("Glossary", "Oximetry wizard"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports the recording of a pulse oximeter: over Bluetooth, by cable or from a file."),
      QT_TRANSLATE_NOOP("Glossary", "Contec CMS50 over Bluetooth: close the phone app and turn on Bluetooth in the oximeter's menu first."),
      "", "spo2" },
    { "ui.menu.actionImport_ZEO_Data", QT_TRANSLATE_NOOP("Glossary", "Import ZEO data"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports sleep stages from a ZEO sleep monitor's CSV file."),
      "",
      "", "" },
    { "ui.menu.actionImport_Dreem_Data", QT_TRANSLATE_NOOP("Glossary", "Import Dreem data"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports sleep data from a Dreem headband's export file."),
      "",
      "", "" },
    { "ui.menu.actionImport_AppleHealth_Data", QT_TRANSLATE_NOOP("Glossary", "Import Apple Health data"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports oxygen, pulse and sleep from an Apple Health export, for example from an Apple Watch."),
      "",
      "", "spo2" },
    { "ui.menu.actionImport_Somnopose_Data", QT_TRANSLATE_NOOP("Glossary", "Import Somnopose data"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports sleeping position from the Somnopose phone app's file."),
      "",
      "", "" },
    { "ui.menu.actionImport_Viatom_Data", QT_TRANSLATE_NOOP("Glossary", "Import Viatom/Wellue data"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports the recordings of Viatom or Wellue oximeters (O2Ring and others) from their files."),
      "",
      "", "spo2" },
    { "ui.menu.actionImport_RemStar_MSeries_Data", QT_TRANSLATE_NOOP("Glossary", "Import RemStar M-Series data"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Imports data of the old Philips RemStar M-Series devices."),
      "",
      "", "" },
    { "ui.menu.actionTime_Corrections", QT_TRANSLATE_NOOP("Glossary", "Time corrections"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Fixes the time of nights recorded with a wrong device clock: time zone, travel, summer time or a clock reset."),
      QT_TRANSLATE_NOOP("Glossary", "Use it when nights show up at the wrong hour or on the wrong day."),
      "", "" },
    { "ui.menu.actionDrift_Analysis", QT_TRANSLATE_NOOP("Glossary", "Drift analysis"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Measures how the device clock drifted over time and suggests a correction."),
      "",
      "", "" },
    { "ui.menu.action_Rebuild_Oximetry_Index", QT_TRANSLATE_NOOP("Glossary", "Automatic oximetry cleanup"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Goes through the oximetry recordings and removes the obviously wrong values at their start and end."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "It changes the stored oximetry of every night it cleans."), "spo2" },
    { "ui.menu.actionRecalculateAnalysis", QT_TRANSLATE_NOOP("Glossary", "Recalculate analysis"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu"),
      QT_TRANSLATE_NOOP("Glossary", "Runs OSCAR's own analysis of all nights again, for example after changing its settings."),
      QT_TRANSLATE_NOOP("Glossary", "Needed only after changing the analysis settings; new nights are analysed on import."),
      QT_TRANSLATE_NOOP("Glossary", "It takes a while and replaces the earlier analysis results."), "an_ahi" },
    { "ui.menu.actionPurge_Current_Day", QT_TRANSLATE_NOOP("Glossary", "Purge CPAP of this day"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Current Selected Day"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the device data of the selected day; notes and oximetry stay."),
      QT_TRANSLATE_NOOP("Glossary", "Use it to load a night again after a faulty import."),
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing the card again, if the card still holds that night."), "" },
    { "ui.menu.actionPurgeCurrentDayOximetry", QT_TRANSLATE_NOOP("Glossary", "Purge oximetry of this day"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Current Selected Day"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the oximetry of the selected day."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing the oximeter recording again."), "spo2" },
    { "ui.menu.actionPurgeCurrentDaySleepStage", QT_TRANSLATE_NOOP("Glossary", "Purge sleep stages of this day"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Current Selected Day"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the sleep stage data of the selected day."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing it again."), "" },
    { "ui.menu.actionPurgeCurrentDayPosition", QT_TRANSLATE_NOOP("Glossary", "Purge position of this day"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Current Selected Day"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the sleeping position data of the selected day."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing it again."), "" },
    { "ui.menu.actionPurgeCurrentDayAllExceptNotes", QT_TRANSLATE_NOOP("Glossary", "Purge all but notes"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Current Selected Day"),
      QT_TRANSLATE_NOOP("Glossary", "Removes all data of the selected day except the notes and bookmarks."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing the card again, if the card still holds that night."), "" },
    { "ui.menu.actionPurgeCurrentDayAll", QT_TRANSLATE_NOOP("Glossary", "Purge all including notes"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Current Selected Day"),
      QT_TRANSLATE_NOOP("Glossary", "Removes everything recorded for the selected day: device data, oximetry, notes and bookmarks."),
      QT_TRANSLATE_NOOP("Glossary", "To load a night again, choose \"CPAP\" in the same menu instead: it keeps the notes."),
      QT_TRANSLATE_NOOP("Glossary", "Notes and bookmarks are lost for good; device data comes back only by importing the card again."), "" },
    { "ui.menu.actionPurgeRangeOfDays", QT_TRANSLATE_NOOP("Glossary", "Purge range of days"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the data of several days at once; you choose the dates and the kinds of data."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing the card again, if the card still holds that night."), "" },
    { "ui.menu.actionPurgeCurrentDaysOximetry", QT_TRANSLATE_NOOP("Glossary", "Purge oximetry of the shown days"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced → Purge Oximetry Data"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the oximetry of the days now shown."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "Comes back only by importing the oximeter recordings again."), "spo2" },
    { "ui.menu.actionPurgeAllTimeCorrections", QT_TRANSLATE_NOOP("Glossary", "Purge all time corrections"),
      QT_TRANSLATE_NOOP("Glossary", "Data menu → Advanced"),
      QT_TRANSLATE_NOOP("Glossary", "Removes every time correction made in \"Time Corrections\"; the nights return to the device's own clock."),
      "",
      QT_TRANSLATE_NOOP("Glossary", "The corrections cannot be brought back; you would have to make them again."), "" },
    { "ui.menu.action_Check_for_Updates", QT_TRANSLATE_NOOP("Glossary", "Check for updates"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu"),
      QT_TRANSLATE_NOOP("Glossary", "Looks for a newer OSCAR version on the internet."),
      "",
      "", "" },
    { "ui.menu.actionOnline_Users_Guide", QT_TRANSLATE_NOOP("Glossary", "Online user's guide"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the OSCAR guide in the web browser."),
      "",
      "", "" },
    { "ui.menu.action_Frequently_Asked_Questions", QT_TRANSLATE_NOOP("Glossary", "Frequently asked questions"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the OSCAR FAQ in the web browser."),
      "",
      "", "" },
    { "ui.menu.actionSleep_Disorder_Terms_Glossary", QT_TRANSLATE_NOOP("Glossary", "Sleep disorder terms glossary"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu"),
      QT_TRANSLATE_NOOP("Glossary", "Opens a list of sleep and CPAP terms in the web browser."),
      QT_TRANSLATE_NOOP("Glossary", "The help panel (View menu) explains OSCAR's own figures in place."),
      "", "" },
    { "ui.menu.actionChange_Language", QT_TRANSLATE_NOOP("Glossary", "Change language"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu"),
      QT_TRANSLATE_NOOP("Glossary", "Chooses the language of OSCAR's menus and pages."),
      QT_TRANSLATE_NOOP("Glossary", "OSCAR restarts to apply it."),
      "", "" },
    { "ui.menu.actionDebug", QT_TRANSLATE_NOOP("Glossary", "Debug pane"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Shows a panel with OSCAR's technical messages."),
      QT_TRANSLATE_NOOP("Glossary", "Useful only when reporting a problem."),
      "", "" },
    { "ui.menu.actionShow_Performance_Counters", QT_TRANSLATE_NOOP("Glossary", "Performance information"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Shows how long OSCAR spent loading and drawing."),
      QT_TRANSLATE_NOOP("Glossary", "Only for troubleshooting slowness."),
      "", "" },
    { "ui.menu.actionCheck_Database_Integrity", QT_TRANSLATE_NOOP("Glossary", "Check database integrity"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Checks the OSCAR database file for damage."),
      QT_TRANSLATE_NOOP("Glossary", "Run it if OSCAR behaves oddly after a crash or a power cut."),
      "", "" },
    { "ui.menu.actionCompress_Database", QT_TRANSLATE_NOOP("Glossary", "Compress database"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Rewrites the database file to free unused space."),
      QT_TRANSLATE_NOOP("Glossary", "Rarely needed: only after deleting a lot of data."),
      QT_TRANSLATE_NOOP("Glossary", "It can take several minutes; do not close OSCAR meanwhile."), "" },
    { "ui.menu.actionCreate_Card_zip", QT_TRANSLATE_NOOP("Glossary", "Zip of the CPAP card"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Packs the contents of the device card into one zip file."),
      QT_TRANSLATE_NOOP("Glossary", "Helps developers when a device's data does not import correctly."),
      "", "" },
    { "ui.menu.actionCreate_Log_zip", QT_TRANSLATE_NOOP("Glossary", "Zip of diagnostic logs"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Packs OSCAR's log files into one zip file to attach to a problem report."),
      "",
      "", "" },
    { "ui.menu.actionCreate_OSCAR_Data_zip", QT_TRANSLATE_NOOP("Glossary", "Zip of the database"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Packs the whole OSCAR database into one zip file."),
      QT_TRANSLATE_NOOP("Glossary", "For a full copy of everything; a profile backup is smaller and usually enough."),
      "", "" },
    { "ui.menu.actionReport_a_Bug", QT_TRANSLATE_NOOP("Glossary", "Report an issue"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the page for reporting a problem with OSCAR."),
      "",
      "", "" },
    { "ui.menu.actionSystem_Information", QT_TRANSLATE_NOOP("Glossary", "System information"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu → Troubleshooting"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the OSCAR version and computer details to copy into a problem report."),
      "",
      "", "" },
    { "ui.menu.action_About", QT_TRANSLATE_NOOP("Glossary", "About OSCAR"),
      QT_TRANSLATE_NOOP("Glossary", "Help menu"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the version, the authors and the licence."),
      "",
      "", "" },
    { "ui.main.profilesButton", QT_TRANSLATE_NOOP("Glossary", "Profiles"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the list of profiles to switch between people or devices."),
      "",
      "", "" },
    { "ui.main.statisticsButton", QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Statistics page: tables of the figures for several periods."),
      "",
      "", "median,p95" },
    { "ui.main.dailyButton", QT_TRANSLATE_NOOP("Glossary", "Daily"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Daily page: one night in detail."),
      "",
      "", "" },
    { "ui.main.overviewButton", QT_TRANSLATE_NOOP("Glossary", "Overview"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Overview page: one bar per night."),
      "",
      "", "" },
    { "ui.main.oximetryButton", QT_TRANSLATE_NOOP("Glossary", "Oximetry"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the oximetry import wizard."),
      "",
      "", "spo2" },
    { "ui.main.importButton", QT_TRANSLATE_NOOP("Glossary", "Import"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Imports new nights from the device's SD card."),
      QT_TRANSLATE_NOOP("Glossary", "Nights already in OSCAR are skipped."),
      "", "" },
    { "ui.main.helpButton", QT_TRANSLATE_NOOP("Glossary", "Help"),
      QT_TRANSLATE_NOOP("Glossary", "Left toolbar"),
      QT_TRANSLATE_NOOP("Glossary", "Opens OSCAR's help pages."),
      "",
      "", "" },
    { "ui.main.filterBookmarks", QT_TRANSLATE_NOOP("Glossary", "Bookmark filter"),
      QT_TRANSLATE_NOOP("Glossary", "Right sidebar → Bookmarks"),
      QT_TRANSLATE_NOOP("Glossary", "Shows only the bookmarks whose text contains what you type."),
      "",
      "", "" },
    { "ui.main.filterBookmarksButton", QT_TRANSLATE_NOOP("Glossary", "Clear filter"),
      QT_TRANSLATE_NOOP("Glossary", "Right sidebar → Bookmarks"),
      QT_TRANSLATE_NOOP("Glossary", "Clears the bookmark filter and shows all bookmarks."),
      "",
      "", "" },
    { "ui.main.reportModeStandard", QT_TRANSLATE_NOOP("Glossary", "Standard report"),
      QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the figures for the last night, week, month, six months and year side by side."),
      QT_TRANSLATE_NOOP("Glossary", "The usual choice to see how therapy goes."),
      "", "period" },
    { "ui.main.reportModeMonthly", QT_TRANSLATE_NOOP("Glossary", "Monthly report"),
      QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "Shows one column per calendar month."),
      QT_TRANSLATE_NOOP("Glossary", "Good for seeing slow changes over a year."),
      "", "period" },
    { "ui.main.reportModeRange", QT_TRANSLATE_NOOP("Glossary", "Date range report"),
      QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the figures for the dates you choose below."),
      QT_TRANSLATE_NOOP("Glossary", "Use it to compare the time before and after a change of mask or settings."),
      "", "period" },
    { "ui.main.reportModeSettings", QT_TRANSLATE_NOOP("Glossary", "Settings comparison"),
      QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "Groups the nights by device settings and compares how each set of settings worked."),
      QT_TRANSLATE_NOOP("Glossary", "Look at the column with more nights first: a few nights say little."),
      "", "best_value" },
    { "ui.main.statStartDate", QT_TRANSLATE_NOOP("Glossary", "Start date"),
      QT_TRANSLATE_NOOP("Glossary", "Statistics → Date Range"),
      QT_TRANSLATE_NOOP("Glossary", "The first day of the date range report."),
      "",
      "", "" },
    { "ui.main.statEndDate", QT_TRANSLATE_NOOP("Glossary", "End date"),
      QT_TRANSLATE_NOOP("Glossary", "Statistics → Date Range"),
      QT_TRANSLATE_NOOP("Glossary", "The last day of the date range report."),
      "",
      "", "" },
    { "ui.daily.prevDayButton", QT_TRANSLATE_NOOP("Glossary", "Previous day"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Goes to the day before."),
      "",
      "", "" },
    { "ui.daily.calButton", QT_TRANSLATE_NOOP("Glossary", "Calendar"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows or hides the calendar."),
      "",
      "", "" },
    { "ui.daily.nextDayButton", QT_TRANSLATE_NOOP("Glossary", "Next day"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Goes to the day after."),
      "",
      "", "" },
    { "ui.daily.todayButton", QT_TRANSLATE_NOOP("Glossary", "Last day with data"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Goes to the most recent day that has data."),
      "",
      "", "" },
    { "ui.daily.calendar", QT_TRANSLATE_NOOP("Glossary", "Calendar"),
      QT_TRANSLATE_NOOP("Glossary", "Daily"),
      QT_TRANSLATE_NOOP("Glossary", "Picks the day to show. Days with data are marked; the colour shows whether the night met the usage target."),
      "",
      "", "compliance" },
    { "ui.daily.evViewSlider", QT_TRANSLATE_NOOP("Glossary", "Event view window"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Events"),
      QT_TRANSLATE_NOOP("Glossary", "How many minutes around an event the graphs show when you click it in the event list."),
      QT_TRANSLATE_NOOP("Glossary", "A few minutes show the breathing before and after the event."),
      "", "" },
    { "ui.daily.eventsCombo", QT_TRANSLATE_NOOP("Glossary", "Event types"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Chooses which event flags the Daily graphs show."),
      QT_TRANSLATE_NOOP("Glossary", "Hide the rare types to make the busy ones easier to see."),
      "", "event_flags" },
    { "ui.daily.graphCombo", QT_TRANSLATE_NOOP("Glossary", "Graphs"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Chooses which graphs the Daily page shows."),
      "",
      "", "" },
    { "ui.daily.graphHelp", QT_TRANSLATE_NOOP("Glossary", "Graph hints"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows how to zoom, scroll and resize the graphs with the mouse and keys."),
      "",
      "", "" },
    { "ui.daily.layout", QT_TRANSLATE_NOOP("Glossary", "Layout"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Saves the current set, order and heights of the graphs under a name, or restores a saved one."),
      "",
      "", "" },
    { "ui.daily.alignButton", QT_TRANSLATE_NOOP("Glossary", "Align"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Lines up an oximeter or another device with the CPAP data of this night when their clocks differ."),
      QT_TRANSLATE_NOOP("Glossary", "Use it when desaturations clearly lag or lead the apneas."),
      "", "spo2" },
    { "ui.daily.addBookmarkButton", QT_TRANSLATE_NOOP("Glossary", "Add bookmark"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Bookmarks"),
      QT_TRANSLATE_NOOP("Glossary", "Marks the part of the night shown in the graphs, with a note, to come back to it later."),
      "",
      "", "" },
    { "ui.daily.removeBookmarkButton", QT_TRANSLATE_NOOP("Glossary", "Remove bookmark"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Bookmarks"),
      QT_TRANSLATE_NOOP("Glossary", "Removes the selected bookmark."),
      "",
      "", "" },
    { "ui.daily.JournalNotesItalic", QT_TRANSLATE_NOOP("Glossary", "Italic"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Makes the selected note text italic."),
      "",
      "", "" },
    { "ui.daily.JournalNotesBold", QT_TRANSLATE_NOOP("Glossary", "Bold"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Makes the selected note text bold."),
      "",
      "", "" },
    { "ui.daily.JournalNotesUnderline", QT_TRANSLATE_NOOP("Glossary", "Underline"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Underlines the selected note text."),
      "",
      "", "" },
    { "ui.daily.JournalNotesColour", QT_TRANSLATE_NOOP("Glossary", "Colour"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Colours the selected note text."),
      "",
      "", "" },
    { "ui.daily.JournalNotesFontsize", QT_TRANSLATE_NOOP("Glossary", "Font size"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Changes the size of the selected note text."),
      "",
      "", "" },
    { "ui.daily.ZombieSpinBox", QT_TRANSLATE_NOOP("Glossary", "Feeling"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "How you felt after the night, as a number; a dash means not set."),
      QT_TRANSLATE_NOOP("Glossary", "Fill it in regularly to compare with AHI and usage over time."),
      "", "" },
    { "ui.daily.ZombieSlider", QT_TRANSLATE_NOOP("Glossary", "Feeling"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "How you felt after the night, set with a slider."),
      "",
      "", "" },
    { "ui.daily.Units10_100", QT_TRANSLATE_NOOP("Glossary", "Feeling range"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Switches the feeling scale between 0–10 and 0–100."),
      "",
      "", "" },
    { "ui.daily.weightSpinBox", QT_TRANSLATE_NOOP("Glossary", "Weight"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Notes"),
      QT_TRANSLATE_NOOP("Glossary", "Your weight on this day. With a height in the profile, OSCAR shows the BMI."),
      QT_TRANSLATE_NOOP("Glossary", "Weight changes can change the pressure needed, so it is worth noting."),
      "", "" },
    { "ui.daily.searchHelpButton", QT_TRANSLATE_NOOP("Glossary", "Search help"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Explains how to search the nights for a condition."),
      "",
      "", "" },
    { "ui.daily.searchMatchButton", QT_TRANSLATE_NOOP("Glossary", "Condition"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Chooses what to search for: an event type, a figure such as AHI or leak, notes, bookmarks and more."),
      "",
      "", "" },
    { "ui.daily.searchAddMatchButton", QT_TRANSLATE_NOOP("Glossary", "Add condition"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Adds the condition to the search."),
      "",
      "", "" },
    { "ui.daily.searchClearButton", QT_TRANSLATE_NOOP("Glossary", "Clear"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Clears the search and its results."),
      "",
      "", "" },
    { "ui.daily.searchStartButton", QT_TRANSLATE_NOOP("Glossary", "Start search"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Searches the nights for the condition; click a result to open that day."),
      "",
      "", "" },
    { "ui.daily.searchCommandButton", QT_TRANSLATE_NOOP("Glossary", "Search for"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the list of things you can search for."),
      "",
      "", "" },
    { "ui.daily.searchOperationCombo", QT_TRANSLATE_NOOP("Glossary", "Comparison"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "How to compare: greater than, less than, equal and so on."),
      "",
      "", "" },
    { "ui.daily.searchOperationButton", QT_TRANSLATE_NOOP("Glossary", "Comparison"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "Changes how the value is compared."),
      "",
      "", "" },
    { "ui.daily.searchValueDouble", QT_TRANSLATE_NOOP("Glossary", "Value"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "The number to compare with."),
      "",
      "", "" },
    { "ui.daily.searchValueInteger", QT_TRANSLATE_NOOP("Glossary", "Value"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "The whole number to compare with."),
      "",
      "", "" },
    { "ui.daily.searchValueText", QT_TRANSLATE_NOOP("Glossary", "Text"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "The text to look for in notes or bookmarks."),
      "",
      "", "" },
    { "ui.daily.searchProgress", QT_TRANSLATE_NOOP("Glossary", "Progress"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "How far the search has gone through the nights."),
      "",
      "", "" },
    { "ui.daily.searchFound", QT_TRANSLATE_NOOP("Glossary", "Found"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "How many days matched."),
      "",
      "", "" },
    { "ui.daily.searchMinMax", QT_TRANSLATE_NOOP("Glossary", "Smallest and largest"),
      QT_TRANSLATE_NOOP("Glossary", "Daily → Search"),
      QT_TRANSLATE_NOOP("Glossary", "The smallest and largest value among the days found."),
      "",
      "", "" },
    { "ui.overview.rangeCombo", QT_TRANSLATE_NOOP("Glossary", "Period"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Chooses the period shown: last week, month, several months, everything or your own dates."),
      QT_TRANSLATE_NOOP("Glossary", "A month is a good start; longer periods show slow trends."),
      "", "period" },
    { "ui.overview.dateStart", QT_TRANSLATE_NOOP("Glossary", "Start date"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "The first day shown."),
      "",
      "", "" },
    { "ui.overview.dateEnd", QT_TRANSLATE_NOOP("Glossary", "End date"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "The last day shown."),
      "",
      "", "" },
    { "ui.overview.zoomButton", QT_TRANSLATE_NOOP("Glossary", "Reset view"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the whole chosen period again after zooming in."),
      "",
      "", "" },
    { "ui.overview.graphCombo", QT_TRANSLATE_NOOP("Glossary", "Graphs"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Chooses which graphs the Overview shows."),
      "",
      "", "" },
    { "ui.overview.graphHelp", QT_TRANSLATE_NOOP("Glossary", "Graph hints"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows how to zoom and scroll the graphs with the mouse and keys."),
      "",
      "", "" },
    { "ui.overview.layout", QT_TRANSLATE_NOOP("Glossary", "Layout"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → bottom bar"),
      QT_TRANSLATE_NOOP("Glossary", "Saves the current set and heights of the graphs under a name, or restores a saved one."),
      "",
      "", "" },
    { "ui.overview.presetButton_0", QT_TRANSLATE_NOOP("Glossary", "All"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows your own choice of graphs from the graph list."),
      "",
      "", "" },
    { "ui.overview.presetButton_1", QT_TRANSLATE_NOOP("Glossary", "Therapy"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the main therapy graphs: usage, AHI, pressure and leak."),
      QT_TRANSLATE_NOOP("Glossary", "Start here to see whether therapy works."),
      "", "ahi,usage" },
    { "ui.overview.presetButton_2", QT_TRANSLATE_NOOP("Glossary", "Mask & Leaks"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the graphs that tell how well the mask fits: leaks and large leaks."),
      "",
      "", "leak" },
    { "ui.overview.presetButton_3", QT_TRANSLATE_NOOP("Glossary", "Oxygen"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the oximetry graphs: SpO2, time below 90 % and pulse."),
      QT_TRANSLATE_NOOP("Glossary", "Useful only on nights with an oximeter."),
      "", "spo2" },
    { "ui.overview.presetButton_4", QT_TRANSLATE_NOOP("Glossary", "Analysis"),
      QT_TRANSLATE_NOOP("Glossary", "Overview → top bar"),
      QT_TRANSLATE_NOOP("Glossary", "Shows the graphs of OSCAR's own analysis: its AHI, flow limitation and Glasgow Index."),
      "",
      "", "an_ahi" },
    { "ui.welcome.importButton", QT_TRANSLATE_NOOP("Glossary", "CPAP importer"),
      QT_TRANSLATE_NOOP("Glossary", "Home page"),
      QT_TRANSLATE_NOOP("Glossary", "Imports new nights from the device's SD card."),
      QT_TRANSLATE_NOOP("Glossary", "Nights already in OSCAR are skipped, so importing the same card again is safe."),
      "", "" },
    { "ui.welcome.oximetryButton", QT_TRANSLATE_NOOP("Glossary", "Oximetry wizard"),
      QT_TRANSLATE_NOOP("Glossary", "Home page"),
      QT_TRANSLATE_NOOP("Glossary", "Imports a pulse oximeter's recording."),
      "",
      "", "spo2" },
    { "ui.welcome.dailyButton", QT_TRANSLATE_NOOP("Glossary", "Daily view"),
      QT_TRANSLATE_NOOP("Glossary", "Home page"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Daily page: one night in detail."),
      "",
      "", "" },
    { "ui.welcome.overviewButton", QT_TRANSLATE_NOOP("Glossary", "Overview"),
      QT_TRANSLATE_NOOP("Glossary", "Home page"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Overview page: one bar per night."),
      "",
      "", "" },
    { "ui.welcome.statisticsButton", QT_TRANSLATE_NOOP("Glossary", "Statistics"),
      QT_TRANSLATE_NOOP("Glossary", "Home page"),
      QT_TRANSLATE_NOOP("Glossary", "Opens the Statistics page."),
      "",
      "", "" },


    // ---- preferences
    { "ui.prefs.timeEdit", QT_TRANSLATE_NOOP("Glossary", "Day Split Time"),
      QT_TRANSLATE_NOOP("Glossary", "Preferences → Import"),
      QT_TRANSLATE_NOOP("Glossary", "Sessions that start before this time are counted for the previous day."),
      QT_TRANSLATE_NOOP("Glossary", "Midday (12:00) suits most people. Move it only if you sleep during the day."), "", "sessions" },
};
// clang-format on

// the controls whose action deletes data, recalculates or replaces what was imported
const char *const kCautionKeys[] = {
    "ui.menu.actionDatabaseNew",
    "ui.menu.actionDatabaseOpen",
    "ui.menu.actionDatabaseDelete",
    "ui.menu.actionRestore_Profile",
    "ui.menu.action_Standard_Graph_Order",
    "ui.menu.action_Advanced_Graph_Order",
    "ui.menu.action_Reset_Graph_Layout",
    "ui.menu.action_Rebuild_Oximetry_Index",
    "ui.menu.actionRecalculateAnalysis",
    "ui.menu.actionPurge_Current_Day",
    "ui.menu.actionPurgeCurrentDayOximetry",
    "ui.menu.actionPurgeCurrentDaySleepStage",
    "ui.menu.actionPurgeCurrentDayPosition",
    "ui.menu.actionPurgeCurrentDayAllExceptNotes",
    "ui.menu.actionPurgeCurrentDayAll",
    "ui.menu.actionPurgeRangeOfDays",
    "ui.menu.actionPurgeCurrentDaysOximetry",
    "ui.menu.actionPurgeAllTimeCorrections",
    "ui.menu.actionCompress_Database",
};

} // namespace

const UiGlossaryRaw *uiGlossaryEntries(int &count)
{
    count = int(sizeof(kUiEntries) / sizeof(kUiEntries[0]));
    return kUiEntries;
}

QStringList Glossary::cautionKeys()
{
    QStringList out;
    for (const char *k : kCautionKeys) out << QString::fromLatin1(k);
    return out;
}
